// <auto-generated />
using System;
using ApiNet8ConSwagger.DataContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ApiNet8ConSwagger.Migrations
{
    [DbContext(typeof(DbContextCube))]
    partial class DbContextCubeModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BaseLibrary.Entities.ApplicationUser", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("ApplicationUsers");
                });

            modelBuilder.Entity("WaCube.Models.Articoli", b =>
                {
                    b.Property<string>("ar_codart")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("codditt")
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.Property<short?>("ar_codiva")
                        .HasColumnType("smallint");

                    b.Property<short>("ar_codmarc")
                        .HasColumnType("smallint");

                    b.Property<short>("ar_codtipa")
                        .HasColumnType("smallint");

                    b.Property<string>("ar_confez2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ar_datins")
                        .HasColumnType("datetime2");

                    b.Property<string>("ar_descr")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("ar_famprod")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<short>("ar_gruppo")
                        .HasColumnType("smallint");

                    b.Property<decimal>("ar_pesolor")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ar_pesonet")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ar_qtacon2")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ar_unmis")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.HasKey("ar_codart", "codditt");

                    b.ToTable("Artico", null, t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
